# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: project_environment
channels:
  - defaults
dependencies:
<<<<<<< HEAD
  - python=3.6.8
  - pip=20.0
  - pip:
    # change this when stable version release
    - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/azureml-v2-cli-e2e-test/60864551
    - azure-ml==0.0.60864551
    - numpy==1.18.1
    - tensorflow==2.2.0
=======
  - python=3.7.6
  - pip=20.0
  - pip:
    - mldesigner==0.1.0b4
    - numpy==1.18.1
    - tensorflow==2.2.0
    - protobuf==3.20.0
>>>>>>> main
