name: pytorch_tutorial_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip=21.2.4
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.1
  - pip:
    - mlflow==1.25.1
    - azureml-defaults==1.41.0
    - azureml-mlflow==1.41.0
    - transformers==4.18.0
    - psutil==5.9.0
    - pynvml==11.4.1
    - matplotlib==3.5.1
    - tqdm==4.62.0
