$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: condition_pipeline
settings:
  default_compute: azureml:cpu-cluster
jobs:
  result:
    type: command
    inputs: {}
    outputs: {}
    properties: {}
    component:
      name: condition_func
      version: '1'
      display_name: condition_func
      description: module run logic goes here
      type: command
      inputs: {}
      outputs:
        output:
          type: boolean
          mode: rw_mount
          is_control: true
      command: mldesigner execute --source component_with_boolean_output.py --name
        condition_func --inputs --outputs output="${{outputs.output}}"
      # TODO: replace with mldesigner curated environment
      environment:
        name: test_env
        tags: {}
        version: 1
        image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
        conda_file:
          name: default_environment
          channels:
          - defaults
          dependencies:
          - python=3.8.12
          - pip=21.2.2
          - pip:
            - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2
            - mldesigner==0.0.72212755
            - mlflow
            - azureml-mlflow
      code: ./
      is_deterministic: true
      tags:
        codegenBy: mldesigner
    environment_variables: {}
  node1:
    type: command
    inputs:
      component_in_number: 1
    outputs: {}
    properties: {}
    component: helloworld_component.yaml
  node2:
    type: command
    inputs:
      component_in_number: 2
    component: helloworld_component.yaml
  conditionnode:
    type: if_else
    true_block: ${{parent.jobs.node2}}
    condition: ${{parent.jobs.result.outputs.output}}
    false_block: ${{parent.jobs.node1}}
tags: {}
properties: {}

