$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_data_component
display_name: train_data
description: A example train component
tags:
  author: azureml-sdk-team
# version: 5 # optional, if omitted will use create time as version
type: command
inputs:
  training_data: 
    type: uri_folder
  max_epocs:
    type: integer
    optional: true
    # $[[command code snippet include optional inputs]] to indicate this code need be hidden if optional inputs are not provided
  learning_rate: 
    type: number
    default: 0.01
  learning_rate_schedule: 
    type: string
    enum:
      - time-based
      - step
      - exponential
outputs:
  model_output:
    type: uri_folder
code: ./train_src
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu:1
command: >-
  python train.py 
  --training_data ${{inputs.training_data}} 
  $[[--max_epocs ${{inputs.max_epocs}}]]
  --learning_rate ${{inputs.learning_rate}} 
  --learning_rate_schedule ${{inputs.learning_rate_schedule}}
  --model_output ${{outputs.model_output}}