$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hello_pipeline_settings

settings:
<<<<<<< HEAD
  default_datestore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  force_rerun: true
=======
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
>>>>>>> main
jobs:
  hello_job:
    command: echo 202204190 & echo "hello"
    environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu:23
  world_job:
    command: echo 202204190 & echo "hello"
    environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu:23   