name: train_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.12
  - pip=21.2.2
  - pip:
<<<<<<< HEAD
      - azure-ml==0.0.60864551
      - --extra-index-url https://pypi.org/simple
      - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/azureml-v2-cli-e2e-test/60864551
=======
      - --extra-index-url https://pypi.org/simple
>>>>>>> main
      - git+https://github.com/NVIDIA/dllogger.git@26a0f8f1958de2c0c460925ff6102a4d2486d6cc#egg=dllogger
      - mldesigner==0.1.0b1
      - watchdog==0.10.3
      - torch==1.8.1
      - torchvision==0.9.1
      - tensorboard==2.5.0
      - pillow==8.2.0
      - numpy==1.19.5
      - --extra-index-url=https://developer.download.nvidia.com/compute/redist/
      - nvidia-dali-cuda100
      - azureml-mlflow==1.41.0
      - protobuf==3.20.1
