$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train
display_name: train an image classification model

inputs:
  train_input:
    type: string
  epoch:
    type: integer

outputs:
  train_output:
    type: uri_folder

code: ./src/train.py

environment: azureml:AzureML-pytorch-1.9-ubuntu18.04-py37-cuda11-gpu@latest
command: >-
  python train.py --data-dir ${{inputs.train_input}} --epochs ${{inputs.epoch}} --output-dir ${{outputs.train_output}}
distribution:
  type: pytorch 
  process_count_per_instance: 1


  
