$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: lightgbm-deployment1
type: kubernetes
endpoint_name: my-mlflow
model:
  name: mir-sample-lightgbm-mlflow-model
  version: 1
  path: lightgbm-iris/model
  type: mlflow_model
instance_type: gpuinstance
instance_count: 1